### ISSUE TITLE
sentry-php v3.18 does not support sentry v22.10.0

### ISSUE THREAD

**Issue by simPod** [getsentry/sentry-php#1531]
### How do you use Sentry?

Self-hosted/on-premise

### Version

3.18

### Steps to Reproduce

Use v3.18 with Sentry 22.10.0

### Expected Result

Issues are present in the sentry

### Actual Result

Api calls fail with Bad Request. I guess a call format changed or something.

**Comment by cleptric** [comment]
We did make a change in https://github.com/getsentry/sentry-php/pull/1518 that will send all events to the `/envelope` endpoint in case performance tracing is enabled.
Though, the `/envelope` endpoint was added to self-hosted in version 20.6.0.

Can you share your `Sentry::init` config and any other things that might help us to see what's wrong?

**Comment by simPod** [comment]
this is the bundle config I use 

```yaml
sentry:
    register_error_listener: false
    logger: monolog.logger.sentry-failure
    options:
        attach_stacktrace: true
        prefixes:
            - /path/
        max_request_body_size: always
        send_default_pii: true
        integrations:
            - Sentry\Integration\IgnoreErrorsIntegration
        environment: '%env(ENV)%'
        in_app_include:
            - My\Ns
        release: '{{commit_hash}}'
        traces_sampler: sentry_sampler
        trace_propagation_targets: {  }
        tags: {  }
        in_app_exclude:
            - /path/var/cache/dev
            - /path/vendor
            - /path/var/cache/dev
        class_serializers: {  }
    dsn: '%env(SENTRY_DSN)%'
    tracing:
        enabled: true
        dbal:
            enabled: true
            connections: {  }
        twig:
            enabled: true
        cache:
            enabled: true
        http_client:
            enabled: true
        console:
            excluded_commands:
                - 'messenger:consume'
    register_error_handler: true
    messenger:
        enabled: false
        capture_soft_fails: true
```
