### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by bassrock** [getsentry/sentry-php#271]
Is PHP 7 officially supported? I just upgraded my instances to php 7 but noticed errors stopped sending to Sentry. 

Is this a known issue?

**Comment by dcramer** [comment]
@bassrock we have a failing test, but its purely related to the stacktrace generation

Are you using any non-default options? Is there anything in error log? Can you try ``$client->captureMessage('test')``

**Comment by bassrock** [comment]
Ok so that worked. However this did not:

```php
throw new \Exception("ahhhhh");
```

Also looks like this may have changed: http://php.net/manual/en/language.errors.php7.php

However I am just using Symfony 2 and Monolog so I thought that should not matter.

**Comment by bassrock** [comment]
Monolog config looks like this:

```yaml
monolog:
   handlers:
       console:
           type: console
           verbosity_levels:
                VERBOSITY_NORMAL: INFO
       sentry:
           type:  raven
           dsn:   %sentry_dsn%
           level: error
           client_id: acme.raven.client
```
