### ISSUE TITLE
Code Coverage. Scrutinizer support

### ISSUE THREAD

**Issue by nokitakaze** [getsentry/sentry-php#442]
We should watch for code coverage on this project. Why don't we add support for [scrutinizer](https://github.com/integrations/scrutinizer-ci)?
https://scrutinizer-ci.com/g/yiisoft/yii2/

So we will have [nice badge](https://scrutinizer-ci.com/g/yiisoft/yii2/badges/coverage.png?b=master) and we will see how broken our project is.
![default](https://cloud.githubusercontent.com/assets/9131758/24743115/b11be440-1ab5-11e7-9ce8-f8cbcf442296.PNG)
It\'s good, isn\'t it?

**Comment by ste93cry** [comment]
It's not configured yet, but [here](https://scrutinizer-ci.com/g/getsentry/sentry-php/) we go

**Comment by nokitakaze** [comment]
In my project config (Setting -> Configuration) looks like this
```yaml
tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true

build:
    tests:
        override:
            -
                command: 'phpunit tests --coverage-clover tests/clover.xml --configuration tests/phpunit.xml'
                coverage:
                    file: 'tests/clover.xml'
                    format: 'clover'

filter:
    excluded_paths: [functions/helper/*, templates/*, vendor/*, tests/*]
```

File tests/clover.xml will be created in the process.
My [tests/phpunit.xml](https://github.com/nokitakaze/ascetcms/blob/concept/tests/phpunit.xml).
