### ISSUE TITLE
Integration with monolog reporting errors of all levels

### ISSUE THREAD

**Issue by gliba008** [getsentry/sentry-php#856]
Greetings to you all.
I have a problem with integration with monolog. It logs all levels of errors and changing the configuration doesn't help.

# Repro steps:
- Followed this tutorial to the letter: https://github.com/getsentry/sentry-symfony#installation
- Special attention to this
```
// monolog.yaml

sentry:
  type: service
  id: sentry.monolog.handler
  level: error
```
- Added this to my test controller: 
```
public function testMonolog(LoggerInterface $logger)
{
  $logger->error('test');
  return $this->json('ok');
}
```

# Expected behavior
To receive Error with message 'test'

# Real behavior
Received following errors:
- Populated the TokenStorage with an anonymous Token.
- Matched route "{route}".
- Error 'test'

**Comment by ste93cry** [comment]
The issue is that the Monolog handler just forwards everything to the `captureEvent` method while an error that gets catched by the error handler is first passed through the `ErrorHandlerIntegration` and `FatalErrorHandlerIntegration` that filter out it according to the `error_types` option. I'm not sure about the approach we want to take here, but here some solutions I have in mind (didn't check whether they are possible or not):

- Duplicate the code that filter out the errors to report into the Monolog handler
- Move the code that does the check against the `error_types` option from the `*HandlerIntegration` classes into the `Client::capture*` methods instead

**Comment by B-Galati** [comment]
@gliba008 You might want to check https://github.com/B-Galati/monolog-sentry-handler. There is a Symfony guide that could help you with your setup and long running process.

**Comment by krukru** [comment]
I can confirm this issue as well. Regardless of the level you set in section https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk, the level is always set to Logger::DEBUG in the Handler.
I mitigated this by setting the level parameter thourgh symfony DI

```yml
  sentry.monolog.handler:
    class: Sentry\Monolog\Handler
    arguments:
      $level: 'error'
```

Also the example for setting the handler seems to be missing the handler section
```yml
monolog:
    handler:
        sentry:
          type: service
          id: sentry.monolog.handler
          level: error #this gets ignored
```
